export const reduxTypes = {
    SET_USER_DATA: 'SET-USER-DATA',
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_FRIENDS: 'SET-USERS',
    SET_CURRENT_PAGE: 'SET-CURRENT-PAGE',
    SET_TOTAL_FRIENDS_COUNT: 'SET-TOTAL-FRIENDS-COUNT',
    SET_IS_FETCHING: 'SET-IS-FETCHING',
    SEND_MESSAGE: 'SEND-MESSAGE',
    ADD_POST: 'ADD-POST',
    UPDATE_INPUT_POST_TEXT: 'UPDATE-INPUT-POST-TEXT',
    SET_PROFILE: 'SET-USER-PROFILE',
    SET_STATUS: 'SET-STATUS',
};